modLoader="javafml" #mandatory
loaderVersion="[47,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
issueTrackerURL="https://github.com/Sreeraj-S/JEconomy/issues"
[[mods]] #mandatory
modId="jeconomy" #mandatory
version="${version}" #mandatory
displayName="JEconomy" #mandatory
displayURL="https://sreeraj-s.github.io/my-portfolio/"
#logoFile="icon.png" #optional
authors="Sreeraj S" #optional
description='''
Adds Economy Feature
'''
[[dependencies.jeconomy]] #optional
   modId="forge" #mandatory
   mandatory=true #mandatory
   versionRange="[47,)" #mandatory

[[dependencies.jeconomy]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.20.1,)"

[[dependencies.jeconomy]]
   modId="architectury"
   mandatory=true
   versionRange="[6.5.69,)"
